# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec71ba59b65de7346c362b1404130012df66ae660e1032baca914b5bfa063fb55cbc6d07e9cf540287fd8fcc86c7ebcefd3faad1107124055897b25b030d9ec5

test:
  secret_key_base: 5161013391d29134edfe48be14ed7e1760e1a8b5334b676f6e4e109b9b7b20aec00bdb30a146782fb898d57021ae0c930d2d0ca9de8f2bed26f4712de039ec16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
